export enum FilterType {
  TOP_HEADLINES = "TOP_HEADLINES",
  SPACE = "SPACE",
  CRYPTO = "CRYPTO",
  TECHNOLOGY = "TECHNOLOGY",
  BUSINESS = "BUSINESS",
  ENTERTAINMENT = "ENTERTAINMENT",
  HEALTH = "HEALTH",
  SCIENCE = "SCIENCE",
}
